config/routes.rb
Rails.application.routes.draw do

  root 'garments#index'

  resources :garments

  get '/login' => 'application#login'
  get '/logout' => 'application#logout'
end

app/models/authentication.rb
class Authentication
  attr_reader :encrypted_password, :salt

  def initialize(password, salt = nil)
    @password = password
    @salt = salt
    encrypt_password
  end

  private

  def encrypt_password
    if @password.present?
      @salt ||= BCrypt::Engine.generate_salt
      @encrypted_password = BCrypt::Engine.hash_secret(@password, @salt)
    end
  end
end

app/models/concerns/authenticable.rb
# Interface:
#  attr_reader :username
#  attr_accessor :encrypted_password
#  attr_accessor :salt
module Authenticable
  extend ActiveSupport::Concern

  included do
    attr_accessor :password
    before_save :encrypt_password
    after_save :clear_password
  end

  def authenticate?(login_password)
    challenge = Authentication.new(login_password, salt)
    encrypted_password == challenge.encrypted_password
  end

  private

  def authentication
    @authentication ||= Authentication.new(password, salt)
  end

  def encrypt_password
    if password.present?
      self.salt               = authentication.salt
      self.encrypted_password = authentication.encrypted_password
    end
  end

  def clear_password
    self.password = nil
  end
end

app/models/garment.rb
class Garment
  include Mongoid::Document
  field :name, type: String
  field :sku, type: String
  field :color, type: String
  field :kind, type: String
  field :size, type: String
  field :price, type: Money
  field :brand, type: String
  validates :name, presence: true, length: { minimum: 3, allow_blank: false }
  validates :sku, presence: true, uniqueness: true
end

app/models/user.rb
class User
  include Mongoid::Document
  include Authenticable

  field :username, type: String
  field :encrypted_password, type: String
  field :salt, type: String
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include AccessControl

end

app/controllers/concerns/access_control.rb
module AccessControl
  extend ActiveSupport::Concern

  included do
    before_action :set_current_user
    helper_method :current_user, :logged_in?
  end

  def login
    require_login
  end

  def logout
    render status: :unauthorized
  end

  protected

  def set_current_user
    @current_user = authenticate_with_http_basic do |username, password|
      user = User.where(username: username).first
      user && user.authenticate?(password) ? user : nil
    end
    true # login migh not be required
  end

  def current_user
    @current_user
  end

  def logged_in?
    @current_user.present?
  end

  def require_login
    if logged_in?
      redirect_to root_path
    else
      request_http_basic_authentication
    end
  end
end

app/controllers/garments_controller.rb
class GarmentsController < ApplicationController
  before_action :set_garment, only: %i(new create edit update destroy)
  # before_action :require_login

  def index
    @garments = Garment.all
  end

  def new
  end

  def create
    if @garment.save
      redirect_to garments_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @garment.save
      redirect_to garments_path
    else
      render :edit
    end
  end

  def destroy
    @garment.destroy if @garment
    redirect_to garments_path
  end

  private

  def set_garment
    @garment = params[:id] ? Garment.find_by(id: params[:id]) : Garment.new
    @garment.assign_attributes(garment_params) if @garment && params[:garment]
  end

  def garment_params
    params.require(:garment)
          .permit(:name, :sku, :color, :kind, :size, :price, :brand)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/garments_helper.rb
module GarmentsHelper
end

app/views/application/logout.html.erb
<p>
  You have successfully logged out
  <%= link_to 'Home', root_path %>
</p>

app/views/authentication/_links.html.erb
<% if logged_in? %>
  Hello <b><%= current_user.username %></b> |
  <%= link_to 'Exit', logout_path %>
<% else %>
  <%= link_to 'Login', login_path %>
<% end %>

app/views/garments/_form.html.erb
<%= form_for @garment do |f| %>

  <% if @garment.errors.any? %>
    <!-- replace with simple_form inline errors -->
    <div id="error_explanation">
      <h2>Error</h2>
      <p>
        <%= pluralize(@garment.errors.count, "error") %>
        prohibited this model from being saved:
      </p>
      <ul>
      <% @garment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class='field'>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class='field'>
    <%= f.label :sku %>
    <%= f.text_field :sku %>
  </div>
  <div class='field'>
    <%= f.label :color %>
    <%= f.text_field :color %>
  </div>
  <div class='field'>
    <%= f.label :kind %>
    <%= f.text_field :kind %>
  </div>
  <div class='field'>
    <%= f.label :size %>
    <%= f.text_field :size %>
  </div>
  <div class='field'>
    <%= f.label :price %>
    <%= f.number_field :price, min: 0, step: 0.01 %>
  </div>
  <div class='field'>
    <%= f.label :brand %>
    <%= f.text_field :brand %>
  </div>
  <%= f.submit %>
<% end %>

app/views/garments/_garment.html.erb
<article class='garment'>
  <div class='actions'>
    <%= link_to(t('.edit'), edit_garment_path(garment)) %> |
    <%= link_to(t('.delete'), garment_path(garment),
                method: :delete,
                data: { confirm: t('.comfirm_delete') },
                class: 'danger'
               ) %>
  </div>
  <b><%= garment.name  %></b> [<%= garment.sku %>] <br>
  <b>Color:</b> <%= garment.color %> <br>
  <b>Kind:</b>  <%= garment.kind  %> <br>
  <b>Size:</b>  <%= garment.size  %> <br>

  <b>Price:</b> <%= humanized_money_with_symbol garment.price %> <br>
  <b>Brand:</b> <%= garment.brand %>
</article>

app/views/garments/edit.html.erb
<h2><%= t '.update', name: @garment.name %></h2>
<%= render 'form' %>

app/views/garments/index.html.erb
<h1> <%= t('.title') %></h1>
<section id='garments'>
  <div class='actions'>
    <%= link_to t('.new'), new_garment_path %>
  </div>
  <%= render @garments %>
</section>

app/views/garments/new.html.erb
<h2><%= t '.create'%> </h2>
<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cloth</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <section class="authentication">
    <%= render 'authentication/links' %>
  </section>
  <section id='main'>
    <%= yield %>
  </section>
</body>
</html>